(function(b){var l,n,e,f=Math.max,g=Math.min;l={};l.d=b(document);l.t=function(a){return a.originalEvent.touches.length-1};n=function(){var a=this;this.cv=this.v=this.g=this.i=this.$=this.o=null;this.h=this.w=this.y=this.x=0;this.c=this.$c=null;this.t=0;this.isInit=!1;this.rH=this.eH=this.cH=this.dH=this.pColor=this.fgColor=null;this.scale=1;this.relativeHeight=this.relativeWidth=this.relative=!1;this.$div=null;this.run=function(){var c=function(c,d){for(var b in d)a.o[b]=d[b];a.init();a._configure()._draw()};
if(!this.$.data("kontroled")){this.$.data("kontroled",!0);this.extend();this.o=b.extend({min:this.$.data("min")||0,max:this.$.data("max")||100,stopper:!0,readOnly:this.$.data("readonly"),cursor:!0===this.$.data("cursor")&&30||this.$.data("cursor")||0,thickness:this.$.data("thickness")||.35,lineCap:this.$.data("linecap")||"butt",width:this.$.data("width")||200,height:this.$.data("height")||200,displayInput:null==this.$.data("displayinput")||this.$.data("displayinput"),displayPrevious:this.$.data("displayprevious"),
fgColor:this.$.data("fgcolor")||"#87CEEB",inputColor:this.$.data("inputcolor")||this.$.data("fgcolor")||"#87CEEB",font:this.$.data("font")||"Arial",fontWeight:this.$.data("font-weight")||"bold",inline:!1,step:this.$.data("step")||1,draw:null,change:null,cancel:null,release:null,error:null},this.o);this.$.is("fieldset")?(this.v={},this.i=this.$.find("input"),this.i.each(function(c){var d=b(this);a.i[c]=d;a.v[c]=d.val();d.bind("change",function(){var b={};b[c]=d.val();a.val(b)})}),this.$.find("legend").remove()):
(this.i=this.$,this.v=this.$.val(),""==this.v&&(this.v=this.o.min),this.$.bind("change",function(){a.val(a._validate(a.$.val()))}));!this.o.displayInput&&this.$.hide();this.$c=b(document.createElement("canvas"));"undefined"!==typeof G_vmlCanvasManager&&G_vmlCanvasManager.initElement(this.$c[0]);if(this.c=this.$c[0].getContext?this.$c[0].getContext("2d"):null)return this.scale=(window.devicePixelRatio||1)/(this.c.webkitBackingStorePixelRatio||this.c.mozBackingStorePixelRatio||this.c.msBackingStorePixelRatio||
this.c.oBackingStorePixelRatio||this.c.backingStorePixelRatio||1),this.relativeWidth=0!==this.o.width%1&&this.o.width.indexOf("%"),this.relativeHeight=0!==this.o.height%1&&this.o.height.indexOf("%"),this.relative=this.relativeWidth||this.relativeHeight,this.$div=b('<div style="'+(this.o.inline?"display:inline;":"")+'"></div>'),this.$.wrap(this.$div).before(this.$c),this.$div=this.$.parent(),this._carve(),this.v instanceof Object?(this.cv={},this.copy(this.v,this.cv)):this.cv=this.v,this.$.bind("configure",
c).parent().bind("configure",c),this._listen()._configure()._xy().init(),this.isInit=!0,this._draw(),this;this.o.error&&this.o.error()}};this._carve=function(){if(this.relative){var a=this.relativeWidth?this.$div.parent().width()*parseInt(this.o.width)/100:this.$div.parent().width(),b=this.relativeHeight?this.$div.parent().height()*parseInt(this.o.height)/100:this.$div.parent().height();this.w=this.h=Math.min(a,b)}else this.w=this.o.width,this.h=this.o.height;this.$div.css({width:this.w+"px",height:this.h+
"px"});this.$c.attr({width:this.w,height:this.h});1!==this.scale&&(this.$c[0].width*=this.scale,this.$c[0].height*=this.scale,this.$c.width(this.w),this.$c.height(this.h));return this};this._draw=function(){var c=!0;a.g=a.c;a.clear();a.dH&&(c=a.dH());!1!==c&&a.draw()};this._touch=function(c){var b=function(c){c=a.xy2val(c.originalEvent.touches[a.t].pageX,c.originalEvent.touches[a.t].pageY);c==a.cv||a.cH&&!1===a.cH(c)||(a.change(a._validate(c)),a._draw())};this.t=l.t(c);b(c);l.d.bind("touchmove.k",
b).bind("touchend.k",function(){l.d.unbind("touchmove.k touchend.k");a.rH&&!1===a.rH(a.cv)||a.val(a.cv)});return this};this._mouse=function(c){var b=function(c){c=a.xy2val(c.pageX,c.pageY);c==a.cv||a.cH&&!1===a.cH(c)||(a.change(a._validate(c)),a._draw())};b(c);l.d.bind("mousemove.k",b).bind("keyup.k",function(c){27===c.keyCode&&(l.d.unbind("mouseup.k mousemove.k keyup.k"),a.eH&&!1===a.eH()||a.cancel())}).bind("mouseup.k",function(c){l.d.unbind("mousemove.k mouseup.k keyup.k");a.rH&&!1===a.rH(a.cv)||
a.val(a.cv)});return this};this._xy=function(){var a=this.$c.offset();this.x=a.left;this.y=a.top;return this};this._listen=function(){this.o.readOnly?this.$.attr("readonly","readonly"):(this.$c.bind("mousedown",function(c){c.preventDefault();a._xy()._mouse(c)}).bind("touchstart",function(c){c.preventDefault();a._xy()._touch(c)}),this.relative&&b(window).resize(function(){a._carve().init();a._draw()}),this.listen());return this};this._configure=function(){this.o.draw&&(this.dH=this.o.draw);this.o.change&&
(this.cH=this.o.change);this.o.cancel&&(this.eH=this.o.cancel);this.o.release&&(this.rH=this.o.release);this.o.displayPrevious?(this.pColor=this.h2rgba(this.o.fgColor,"0.4"),this.fgColor=this.h2rgba(this.o.fgColor,"0.6")):this.fgColor=this.o.fgColor;return this};this._clear=function(){this.$c[0].width=this.$c[0].width};this._validate=function(a){return~~((0>a?-.5:.5)+a/this.o.step)*this.o.step};this.listen=function(){};this.extend=function(){};this.init=function(){};this.change=function(a){};this.val=
function(a){};this.xy2val=function(a,b){};this.draw=function(){};this.clear=function(){this._clear()};this.h2rgba=function(a,b){var d;a=a.substring(1,7);d=[parseInt(a.substring(0,2),16),parseInt(a.substring(2,4),16),parseInt(a.substring(4,6),16)];return"rgba("+d[0]+","+d[1]+","+d[2]+","+b+")"};this.copy=function(a,b){for(var d in a)b[d]=a[d]}};e=function(){n.call(this);this.w2=this.cursorExt=this.lineWidth=this.radius=this.xy=this.startAngle=null;this.PI2=2*Math.PI;this.extend=function(){this.o=b.extend({bgColor:this.$.data("bgcolor")||
"#EEEEEE",angleOffset:this.$.data("angleoffset")||0,angleArc:this.$.data("anglearc")||360,inline:!0},this.o)};this.val=function(a){if(null!=a)this.v=this.cv=this.o.stopper?f(g(a,this.o.max),this.o.min):a,this.$.val(this.v),this._draw();else return this.v};this.xy2val=function(a,c){var b;b=Math.atan2(a-(this.x+this.w2),-(c-this.y-this.w2))-this.angleOffset;this.angleArc!=this.PI2&&0>b&&-.5<b?b=0:0>b&&(b+=this.PI2);b=~~(.5+b*(this.o.max-this.o.min)/this.angleArc)+this.o.min;this.o.stopper&&(b=f(g(b,
this.o.max),this.o.min));return b};this.listen=function(){var a=this,c=function(c){c.preventDefault();var d=c.originalEvent;c=d.detail||d.wheelDeltaX;d=d.detail||d.wheelDeltaY;c=parseInt(a.$.val())+(0<c||0<d?a.o.step:0>c||0>d?-a.o.step:0);a.cH&&!1===a.cH(c)||a.val(c)},k,d,m=1,e={37:-a.o.step,38:a.o.step,39:a.o.step,40:-a.o.step};this.$.bind("keydown",function(c){var q=c.keyCode;96<=q&&105>=q&&(q=c.keyCode=q-48);k=parseInt(String.fromCharCode(q));isNaN(k)&&(13!==q&&8!==q&&9!==q&&189!==q&&c.preventDefault(),
-1<b.inArray(q,[37,38,39,40])&&(c.preventDefault(),c=parseInt(a.$.val())+e[q]*m,a.o.stopper&&(c=f(g(c,a.o.max),a.o.min)),a.change(c),a._draw(),d=window.setTimeout(function(){m*=2},30)))}).bind("keyup",function(c){isNaN(k)?d&&(window.clearTimeout(d),d=null,m=1,a.val(a.$.val())):a.$.val()>a.o.max&&a.$.val(a.o.max)||a.$.val()<a.o.min&&a.$.val(a.o.min)});this.$c.bind("mousewheel DOMMouseScroll",c);this.$.bind("mousewheel DOMMouseScroll",c)};this.init=function(){if(this.v<this.o.min||this.v>this.o.max)this.v=
this.o.min;this.$.val(this.v);this.w2=this.w/2;this.cursorExt=this.o.cursor/100;this.xy=this.w2*this.scale;this.lineWidth=this.xy*this.o.thickness;this.lineCap=this.o.lineCap;this.radius=this.xy-this.lineWidth/2;this.o.angleOffset&&(this.o.angleOffset=isNaN(this.o.angleOffset)?0:this.o.angleOffset);this.o.angleArc&&(this.o.angleArc=isNaN(this.o.angleArc)?this.PI2:this.o.angleArc);this.angleOffset=this.o.angleOffset*Math.PI/180;this.angleArc=this.o.angleArc*Math.PI/180;this.startAngle=1.5*Math.PI+
this.angleOffset;this.endAngle=1.5*Math.PI+this.angleOffset+this.angleArc;var a=f(String(Math.abs(this.o.max)).length,String(Math.abs(this.o.min)).length,2)+2;this.o.displayInput&&this.i.css({width:(this.w/2+4>>0)+"px",height:(this.w/3>>0)+"px",position:"absolute","vertical-align":"middle","margin-top":(this.w/3>>0)+"px","margin-left":"-"+(3*this.w/4+2>>0)+"px",border:0,background:"none",font:this.o.fontWeight+" "+(this.w/a>>0)+"px "+this.o.font,"text-align":"center",color:this.o.inputColor||this.o.fgColor,
padding:"0px","-webkit-appearance":"none"})||this.i.css({width:"0px",visibility:"hidden"})};this.change=function(a){this.cv=a;this.$.val(a)};this.angle=function(a){return(a-this.o.min)*this.angleArc/(this.o.max-this.o.min)};this.draw=function(){var a=this.g,c=this.angle(this.cv),b=this.startAngle,c=b+c,d,m;d=1;a.lineWidth=this.lineWidth;a.lineCap=this.lineCap;this.o.cursor&&(b=c-this.cursorExt)&&(c+=this.cursorExt);a.beginPath();a.strokeStyle=this.o.bgColor;a.arc(this.xy,this.xy,this.radius,this.endAngle,
this.startAngle,!0);a.stroke();this.o.displayPrevious&&(m=this.startAngle+this.angle(this.v),d=this.startAngle,this.o.cursor&&(d=m-this.cursorExt)&&(m+=this.cursorExt),a.beginPath(),a.strokeStyle=this.pColor,a.arc(this.xy,this.xy,this.radius,d,m,!1),a.stroke(),d=this.cv==this.v);a.beginPath();a.strokeStyle=d?this.o.fgColor:this.fgColor;a.arc(this.xy,this.xy,this.radius,b,c,!1);a.stroke()};this.cancel=function(){this.val(this.v)}};b.fn.dial=b.fn.knob=function(a){return this.each(function(){var c=new e;
c.o=a;c.$=b(this);c.run()}).parent()}})(jQuery);var w=800,h=600,defaultStrokeWidth=1.5,path="/gclabapps/nb/",selectedSymbolName="",selectedColor="#cccccc",projectId="0",sizeDatas={};$(document).ready(function(){initWindowSize();initGraph();initProjectId();initModelGraph();initKnob();initNodeinfoWindowSize();initNodeinfoWindowOpenButton();initNodeinfoWindowCloseButton();initSearchB()});function getPlotDataPath(){return path+"getNetworkPlotData"}
function initGraph(){modelvis=d3.select("#modelChart").append("svg:svg").attr("width",w).attr("height",h).attr("pointer-events","all").append("svg:g").call(d3.behavior.zoom().on("zoom",zoomHandler)).append("svg:g")}
function initd3(){document.getElementById("geneChart").innerHTML="";vis=d3.select("#geneChart").append("svg:svg").attr("width",w).attr("height",h).attr("pointer-events","all").append("svg:g").call(d3.behavior.zoom().on("zoom",zoomHandler)).append("svg:g");vis.append("svg:rect").attr("width",w).attr("height",h).attr("fill","none")}function zoomHandler(){vis.attr("transform","translate("+d3.event.translate+") scale("+1.2*d3.event.scale+")")}
function initProjectId(){projectId=window.location.search.split("=")[1]}function initWindowSize(){w=$(window).width()-20;h=$(window).height()-40}function initKnob(){$(".dial").knob({fgColor:"#56E0F0",min:1,max:500,angleArc:250,angleOffset:-125,width:250,release:function(b){knobSymbolRedraw(b)}})}
function initModelGraph(){document.getElementById("modelChart").style.display="block";document.getElementById("geneChart").style.display="none";var b=getPlotDataPath()+"?num=9999;model=symbol;symbol=module;id="+projectId;d3.json(b,function(b){function n(c,b){return function(d){g.style("stroke-opacity",function(b){thisOpacity=a[d.index+","+b.index]||a[b.index+","+d.index]||d.index==b.index?1:c;this.setAttribute("fill-opacity",thisOpacity);return thisOpacity});f.style("stroke-opacity",function(a){b?
f.attr("class","linkHighLight"):f.attr("class","link");return a.source===d||a.target===d?1:c});f.style("stroke",function(a){return"#aaa"})}}var e=self.force=d3.layout.force().nodes(b.nodes).links(b.links).distance(300).linkStrength(.05).charge(-300).size([w,h]).start(),f=modelvis.selectAll("line.link").data(b.links).enter().append("svg:line").attr("class","link").attr("x1",function(a){return a.source.x}).attr("y1",function(a){return a.source.y}).attr("x2",function(a){return a.target.x}).attr("y2",
function(a){return a.target.y}).style("stroke",function(a){return"#ccc"}),g=modelvis.selectAll("g.node").data(b.nodes).enter().append("svg:g").attr("class","node").call(e.drag);g.append("svg:circle").attr("r",function(a){return 15}).style("fill",function(a){return"#56E0F0"});g.append("svg:text").attr("class","nodetext").attr("dx",12).attr("dy",".35em").text(function(a){return a.name});g.on("mouseover",n(.05,!0));g.on("mouseout",function(){n(0,!1)});g.on("click",function(a,b){var d=a.name;selectedSymbolName=
d;selectedColor=getColorByName(d);$("#modelname").html(selectedSymbolName);document.getElementById("modelChart").style.display="none";document.getElementById("geneChart").style.display="block";initd3();d=getPlotDataPath()+"?num=100;model=symbol;symbol="+d+";id="+projectId;initGneGraph(d);$("#infoContainer").toggle("slide",200)});f.on("click",function(a,b){matchLink(connectedLinks,a)&&f.style("stroke-opacity",function(d){if(d===a)return f.attr("class","link"),1;f.attr("class","linkHighLightSingle");
return 0})});f.on("contextmenu",function(a,b){});var a={};b.links.forEach(function(c){a[c.source.index+","+c.target.index]=1});g.on("contextmenu",function(a,b){});g.on("dblclick",function(a){a.x=400;a.y=300;a.px=400;a.py=300;e.start()});e.on("tick",function(){f.attr("x1",function(a){return a.source.x}).attr("y1",function(a){return a.source.y}).attr("x2",function(a){return a.target.x}).attr("y2",function(a){return a.target.y});g.attr("transform",function(a){return"translate("+a.x+","+a.y+")"})})})}
function initGneGraph(b){d3.json(b,function(b){var n=self.force=d3.layout.force().nodes(b.nodes).links(b.links).charge(-300).gravity(.05).distance(100).linkStrength(.5).size([w,h]).start(),e=vis.selectAll("line.link").data(b.links).enter().append("svg:line").attr("class","link").attr("x1",function(a){return a.source.x}).attr("y1",function(a){return a.source.y}).attr("x2",function(a){return a.target.x}).attr("y2",function(a){return a.target.y}),f=vis.selectAll("g.node").data(b.nodes).enter().append("svg:g").attr("class",
"node").call(n.drag);f.append("svg:circle").attr("r",function(a){return 12}).style("fill",function(a){return"#56E0F0"});f.append("svg:text").attr("class","nodetext").attr("dx",12).attr("dy",".35em").text(function(a){return a.name});f.on("click",function(b,m){return function(t){f.style("stroke-opacity",function(a){thisOpacity=g[t.index+","+a.index]||g[a.index+","+t.index]||t.index==a.index?1:b;this.setAttribute("fill-opacity",thisOpacity);return thisOpacity});a=t.name;c=[];c.push(a);e.style("stroke-opacity",
function(a){m?e.attr("class","linkHighLight"):e.attr("class","link");return a.source===t||a.target===t?(a.source===t?c.push(a.target.name):c.push(a.source.name),k.push(a),1):b});c=c.getUnique();setNodeInfoList(c)}}(.1,!0));e.on("click",function(a,c){matchLink(k,a)&&e.style("stroke-opacity",function(c){if(c===a)return e.attr("class","link"),1;e.attr("class","linkHighLightSingle");return 0})});e.on("mouseover",function(a,c){matchLink(k,a)&&e.style("stroke-width",function(c){return c.source.name==a.source.name&&
c.target.name==a.target.name?"7px":"1.5px"})});e.on("contextmenu",function(a,c){d3.event.preventDefault();e.style("stroke-opacity",function(c){if(c===a){e.attr("class","link");var b=c.source.name;c=c.target.name;document.getElementById("genecard_a").style.display="none";document.getElementById("brainspan_a").style.display="none";document.getElementById("cox_a").style.display="none";document.getElementById("stanford_a").style.display="none";document.getElementById("pubmid_a").setAttribute("href","http://www.ncbi.nlm.nih.gov/pubmed?term=("+
b+")AND("+c+")");document.getElementById("NGPopUp").style.top=mousePos.y+"px";document.getElementById("NGPopUp").style.left=mousePos.x+20+"px";document.getElementById("NGPopUp").style.display="block";cancelTimer();return 1}e.attr("class","linkHighLightSingle");return 0})});var g={};b.links.forEach(function(a){g[a.source.index+","+a.target.index]=1});var a="",c=[],k=[];f.on("contextmenu",function(a,c){d3.event.preventDefault();showAllLinkField();document.getElementById("genecard_a").setAttribute("href",
"http://www.genecards.org/cgi-bin/carddisp.pl?gene="+a.name);document.getElementById("brainspan_a").setAttribute("href","http://www.brainspan.org/rnaseq/search?type=rnaseq&query="+a.name);document.getElementById("pubmid_a").setAttribute("href","http://www.ncbi.nlm.nih.gov/pubmed?term="+a.name);document.getElementById("cox_a").setAttribute("href","http://coxpresdb.jp/cgi-bin/inkeyword.cgi?type=any&word="+a.name);document.getElementById("stanford_a").setAttribute("href","http://web.stanford.edu/group/barres_lab/cgi-bin/igv_cgi_2.py?lname="+
a.name);document.getElementById("NGPopUp").style.top=mousePos.y+"px";document.getElementById("NGPopUp").style.left=mousePos.x+20+"px";document.getElementById("NGPopUp").style.display="block";cancelTimer()});f.on("dblclick",function(a){a.x=400;a.y=300;a.px=400;a.py=300;n.start()});n.on("tick",function(){e.attr("x1",function(a){return a.source.x}).attr("y1",function(a){return a.source.y}).attr("x2",function(a){return a.target.x}).attr("y2",function(a){return a.target.y});f.attr("transform",function(a){return"translate("+
a.x+","+a.y+")"})})})}Array.prototype.getUnique=function(){for(var b={},l=[],n=0,e=this.length;n<e;++n)b.hasOwnProperty(this[n])||(l.push(this[n]),b[this[n]]=1);return l};var timeout=300,closetimer=0;function cancelTimer(){closetimer&&(window.clearTimeout(closetimer),closetimer=null)}function setTimer(b){closetimer=window.setTimeout(function(){document.getElementById(b).style.display="none"},timeout)}var colorIndex=0;
function getColor(){var b="#F73E88 #F74581 #F745F1 #9773FA #7375FA #73A7FA #73EAFA #4EF5CE #45E670 #96E60E #E6D40E #E67A0E".split(" "),l=b[colorIndex];colorIndex+=1;colorIndex>=b.length&&(colorIndex=0);return l}function getColorByName(b){var l={m2:"#0000FF",m3:"#A52A2A",m4:"#00FFFF",m8:"#808080",m9:"#E0FFFF",m11:"#FF00FF",m13:"#800080",m14:"#FF0000",m15:"#FA8072",m16:"#D2B48C",m17:"#40E0D0",m18:"#FFFF00"};b=b.toLowerCase();return l.hasOwnProperty(b)?l[b]:"#cccccc"}var sizeIndex=0;
function getSize(){var b=[4,6,8,10,12,14,16],l=b[sizeIndex];sizeIndex+=1;sizeIndex>=b.length&&(sizeIndex=0);return l}function getSizeByNameSearch(b){return sizeDatas.hasOwnProperty(selectedSymbolName)?"undefined"==typeof sizeDatas[selectedSymbolName][b]?8:10*sizeDatas[selectedSymbolName][b].s+Math.round(5*sizeDatas[selectedSymbolName][b].s):8}
function showAllLinkField(){document.getElementById("genecard_a").style.display="block";document.getElementById("brainspan_a").style.display="block";document.getElementById("pubmid_a").style.display="block";document.getElementById("cox_a").style.display="block";document.getElementById("stanford_a").style.display="block"}
function resetModelSelection(){modelvis.selectAll("line").style("stroke-opacity",.1);modelvis.selectAll("line").style("stroke-width",1.5);modelvis.selectAll(".node").style("fill-opacity",1)}function resetSelection(){vis.selectAll("line").style("stroke-opacity",.1);vis.selectAll("line").style("stroke-width",1.5);vis.selectAll(".node").style("fill-opacity",1)}
function showModules(){document.getElementById("modelChart").style.display="block";document.getElementById("geneChart").style.display="none";$("#infoContainer").toggle("slide",200);$("#modelname").html("")}function matchLink(b,l){for(var n=!1,e=0;e<b.length;e++)if(b[e].source.name==l.source.name&&b[e].target.name==l.target.name){n=!0;break}return n}
function initSlider(){YUI().use("slider",function(b){var l;l=b.one("#horiz_value");l.setData("slider",(new b.Slider({axis:"x",min:0,max:1225,value:100,length:"500px",after:{valueChange:b.bind(function(b){this.set("value",b.newVal)},l)}})).render(".horiz_slider")).on("keyup",function(l){var e=this.getData();l=e.slider;var f=parseInt(this.get("value"),10);e.wait&&e.wait.cancel();e.wait=b.later(200,l,function(){e.wait=null;this.set("value",f)})})})}
function initJQSlider(){$(function(){$("#jqslider").slider({min:0,max:1E3,value:100,slide:function(b,l){$("#horiz_value").val(l.value)}})})}function knobSymbolRedraw(b){initd3();b=getPlotDataPath()+"?num="+b+";model=symbol;symbol="+selectedSymbolName+";id="+projectId;initGneGraph(b)}function symbolRedraw(){initd3();var b=document.getElementById("horiz_value").value,b=getPlotDataPath()+"?num="+b+";model=symbol;symbol="+selectedSymbolName+";id="+projectId;initGneGraph(b)}var mousePos;
window.onmousemove=handleMouseMove;function handleMouseMove(b){b=b||window.event;mousePos={x:b.clientX,y:b.clientY}}function initNodeinfoWindowSize(){var b=0,b=550<h-500?550:h-500;$("#nodeinfo").css("height",b+"px");$("#infowin").css("height",b+"px")}
function setNodeInfoList(b){for(var l="",n=0;n<b.length;n++)l=l+"<div class='nitem'><span class='nname'>"+b[n]+"</span></div>";$("#nodeinfo").html(l);$(".nitem").hover(function(){$(this).addClass("nitem_hover")},function(){$(this).removeClass("nitem_hover")})}
function setInfoWin(b){$.get(path+"getNodeInfoPage?id="+b,function(b){$("#infowin").html("<div id='ibackb'>&lsaquo;&lsaquo;</div>"+b);$("#nodeinfo").hide();$("#infowin").toggle("slide",200);$("#ibackb").click(function(){$("#infowin").hide();$("#nodeinfo").show()})})}function initNodeinfoWindowOpenButton(){$("#infoContainerExpandBut").click(function(){$("#infoContainer").toggle("slide",200);$("#infoContainerExpandBut").hide()})}
function initNodeinfoWindowCloseButton(){$("#hidebar").click(function(){$("#infoContainer").toggle("slide",200);$("#infoContainerExpandBut").show()})}
function getModelEdgeColor(b,l){var n={2:0,3:1,4:2,8:3,9:4,11:5,13:6,14:7,15:8,16:9,17:10,18:11};b=b.replace("M","");l=l.replace("M","");return 0<[[1,.66,-.81,-.44,-.1,.26,-.76,.39,-.56,-.46,-.64,-.63],[.66,1,-.42,-.2,.44,.23,-.78,.81,-.65,-.57,-.96,-.56],[-.81,-.42,1,.0067,.44,-.42,.73,-.08,.3,.65,.46,.32],[-.44,-.2,.0067,1,-.27,.5,.17,-.31,.41,-.4,.058,.59],[-.1,.44,.44,-.27,1,-.11,-.22,.79,-.32,.087,-.31,-.34],[.26,.23,-.42,.5,-.11,1,-.42,.14,-.084,-.62,-.28,.0014],[-.76,-.78,.73,.17,-.22,-.42,
1,-.66,.44,.68,.73,.55],[.39,.81,-.08,-.31,.79,.14,-.66,1,-.59,-.35,-.71,-.6],[-.56,-.65,.3,.41,-.32,-.084,.44,-.59,1,.35,.52,.62],[-.46,-.57,.65,-.4,.087,-.62,.68,-.35,.35,1,.67,.16],[-.64,-.96,.46,.058,-.31,-.28,.73,-.71,.52,.67,1,.46],[-.63,-.56,.32,.59,-.34,.0014,.55,-.6,.62,.16,.46,1]][n[b]][n[l]]?"#F777BB":"#0FCCF2"}
function getASDColor(b){return{ARX:"",NCAPD2:"",PTBP1:"",VIM:"",POLQ:"",HMG20B:"",SRBD1:"",TEAD2:"",RFX2:"",ASAP3:"",FCGBP:"",CDC45:"",MCM4:"",H2AFV:"",MPDZ:"",PDLIM1:"",PTK7:"",HDAC1:"",TTF2:"",CNN3:"",PHF19:"",HSDL2:"",SORBS3:"",KIF18A:"",CAT:"",STIL:"",SDF2L1:"",TROAP:"",BRCA2:"",BNIP2:"",CMTM3:"",SLC16A3:"",RNPEPL1:"",IQGAP2:"",MKI67:"",MSI2:"",WASF2:"",TAGLN2:"",FBXO8:"",FABP5:"",ACAA2:"",BMP1:"",DAG1:"",CTDSP2:"",OPLAH:"",PTTG1IP:"",IQGAP3:"",HIST2H2AC:"",TMEM216:"",PLCD1:"",HIST1H1C:"",SVIL:"",
ECI2:"",PNP:"",GPR56:"",CLIC1:"",RHBDD2:"",DNAH9:"",CAMK1G:"",ADAM22:"",ROS1:"",PTPRN:"",NPFFR2:"",ERLEC1:"",PTPN3:"",SNCB:"",IPCEF1:"",RIMS1:"",CADPS2:"",TESC:"",RAPGEF4:"",PITPNM3:"",SLC22A17:"",SYNGR1:"",CACNA1F:"",SYP:"",NDRG4:"",NOMO1:"",SYT17:"",CTSH:"",SLC17A7:"",TMEM59L:"",SCN1B:"",DNM1:"",KANK1:"",B9D1:"",CNTNAP1:"",DUSP3:"",GABRA4:"",CDH9:"",GABRG2:"",FHL2:"",EPAS1:"",KIF17:"",B4GALT6:"",CASC1:"",PPL:"",SRGN:"",KCNS1:"",SLC12A5:"",NAPB:"",SULT4A1:"",GFAP:"",ATP6V1E1:"",EFR3A:"",POPDC3:"",
XAF1:"",MYH11:"",MICAL2:"",GLS2:"",RAB11FIP5:"",ENPP2:"",HADHB:"",ZNF365:"",STAT4:"",VAMP1:"",C1ORF222:"",SCN1A:"",UNC80:"",IQSEC1:"",C10ORF116:"",ITPR1:"",TDO2:"",TCTEX1D1:"",ADPRHL1:"",THY1:"",GRAMD3:"",NPTN:"",STEAP2:"",CABP1:"",VSNL1:"",ATP1A1:"",SCRG1:"",OXR1:"",GPR146:"",TPP1:"",IDH3A:"",TMEM130:"",SPRYD3:"",BSCL2:"",CPLX1:"",CDK5R2:"",CYP4F11:"",RCAN2:"",THEMIS:"",RAB37:"",C1QTNF1:"",PCSK1:"",RIMS2:"",CTNNA3:"",GRIN2A:"",TSPYL2:"",CEND1:"",METTL7A:"",SV2B:"",KCNIP4:"",MKL2:"",GABRD:"",FHIT:"",
TPK1:"",ANXA6:"",SLC6A17:"",OGDHL:"",ST7:"",WDR54:"",CUL3:"",RPL18:"",NFYC:"",GSTP1:"",THOC5:"",ZMAT5:"",RPS19:"",DSE:"",CCNG1:"",SET:"",CPSF3L:"",EIF3G:"",TRAF7:"",NXT1:"",C20ORF111:"",RPS15A:"",RPS6:"",RPLP1:"",LRRC49:"",SEC11A:"",RPS2:"",RPL10:"",EIF4A1:"",DDB1:"",GPS1:"",CHD2:"",RPS27:"",PACS2:"",RPL14:"",NACA:"",SND1:"",ISY1:"",MGST1:"",KAL1:"",TYMP:"",TRAF3IP2:"",IFI35:"",ZC3HAV1:"",IFIH1:"",BST2:"",LGALS3:"",VAV3:"",FAM189A2:"",AGT:"",SP110:"",SLCO1C1:"",ALDH1L1:"",SLC39A12:"",EN2:"",ANGPTL4:"",
TAP1:"",RAB31:"",AQP4:"",PARP14:"",IFITM1:"",CYP4F3:"",MT1X:"",MT1M:"","HLA-A":"",IRF9:"",MFRP:"",MTMR7:"",AGK:"",NUDCD3:"",ATP6V0A1:"",MYO16:"",SNAP91:"",NGEF:"",CACNB1:"",ATP2B3:"",LNX1:"",NSF:"",DLG3:"",SMAP2:"",EPB41L1:"",DDX24:"",ACOT7:"",EEF1A2:"",USP11:"",AP3B2:"",RAB2A:"",MTMR9:"",GPI:"",CLIP3:"",SLC1A1:"",FBXW7:"",MADD:"",ENO2:"",CAP2:"",GLS:"",ELOVL4:"",KLC1:"",NDFIP1:"",DLG4:"",SUCLA2:"",SCN2A:"",STXBP1:"",FAM8A1:"",ABI2:"",BBS7:"",UBR3:"",FAM134A:"",ATP6V1B2:"",PAK1:"",DLG2:"",EIF4E:"",
RAB6B:"",RAB39B:"",HK1:"",SV2A:"",ATP13A2:"",AP2M1:"",SHANK2:"",CNST:"",BTRC:"",NDEL1:"",SCG5:"",OTUB1:"",LDB2:"",PRKCE:"",CLSTN1:"",C2CD2L:"",SEZ6L2:"",C12ORF68:"",PER1:"",NRXN1:"",ANKRD34A:"",RGS7:"",INPP5J:"",PARK2:"",CYP4X1:"",NKRF:"",ATL1:"",SLC9A6:"",SCAMP5:"",MAGEE1:"",DCTN1:"",PCDHA13:"",PI4KA:"",ABHD14A:"",ICA1:"",CYB561:"",ZMYND11:"",CDH10:"",CAMK2B:"",ST3GAL6:"",PFKP:"",ATP8B1:"",ACHE:"",KIAA0284:"",SGSM3:"",MCF2:"",ZC3H12B:"",FGF9:"",NCALD:"",PIK3CG:"",STX1A:"",EPHB6:"",GLIS3:"",USP46:"",
HTATIP2:"",GALNTL4:"",PRMT8:"",SLC29A1:"",FOXP1:"",DNAJC27:"",SLC25A12:"",RAB7L1:"",APOL3:"",UNC13A:"",CALY:"",CYP2E1:"",SESN2:"",SYNE1:"",ACP2:"",DTNA:"",ACRV1:"",HTR1B:"",AGAP2:"",KIAA0513:"",PCDH10:"",RAB15:"",ATP1B1:"",EPHX1:"",ZNF385B:"",CNTN4:"",ANK2:"",NLGN4X:"",SNTG1:"",EBAG9:"",DOC2A:"",CACNA1C:"",NR3C2:"",INPP1:"",PTPRK:"",ABI3BP:"",ABCA5:"",FMN2:"",MAPK13:"",ATP2B2:"",C9ORF91:"",TPRG1L:"",NPM2:"",PPAPDC3:"",PTCHD1:"",SLITRK5:"",LRFN5:"",IGFBP6:"",CHRM1:"",FRMPD4:"",NPAS2:"",ABCG4:"",SNAPC5:"",
PELI3:"",BAIAP2:"",LPCAT4:"",SCN4B:"",PGBD5:"",CAMK1D:"",CSMD1:"",FAM174B:"",C11ORF87:"",PION:"",EFCAB6:"",PTPRT:"",GRM7:"",CPNE4:"",ASB13:"",LAMB3:"",GYPE:"",DLGAP2:"",CHSY3:"",ITSN2:"",GPRASP1:"",VAMP2:"",CKMT1B:"",GPR162:"",SLC7A2:"",MPO:"",SLC6A13:"",EHD2:"",ZIC2:"",LAMC3:"",TNFRSF1A:"",TGFBR3:"",CYBRD1:"",MCAM:"",FXYD5:"",LAMB1:"",PLTP:"",MYL12A:"",TIMP1:"",EHD4:"",FCGRT:"",PLEKHA4:"",PCOLCE:"",ECM2:"",SLC6A4:"",CPZ:"",SLC15A3:"",COL12A1:"",TBX18:"",SEMA5A:"",PLSCR4:"",FN1:"",VAMP8:"",RDH10:"",
CDKN1A:"",C3:"",RRAS:"",ZFP36:"",PODXL:"",CD68:"",RHBDF2:"",RARRES3:"",EMP1:"",HEY2:"",GNS:"",TMBIM1:"",TLN1:"",LRRC32:"",MYOF:"",IFITM3:"",EMP3:"",MOB3C:"",RBMS3:"",LPP:"",ATP10D:"",ADD3:"",SERPING1:"",ADAM33:"",GJA1:"",MR1:"",DAB2:"",ADAMTS1:"",SLC7A7:"",COLEC12:"",SHC1:"",ITGA5:"",CXCL16:"",DHRS3:"",DDR2:"",DISC1:"",TGFBR2:"",FBN1:"",B2M:"",RAB3IL1:"",SDC2:"",ADORA2B:"",CD14:"",TMEM51:"",LAMB2:"",MMRN2:"",ANO6:"",ZNF366:"",CDH5:"",NQO1:"",FAM89A:"",BGN:"",ANXA2:"",SRPR:"",OAF:"",PROS1:"",IFITM2:"",
COL4A1:"",S100A16:"",ADA:"",LRP10:"",S100A10:"",TGM2:"",PSMB8:"",CEBPD:"",MLL5:"",BAZ1B:"",TRIO:"",MLL3:"",ARHGEF10L:"",ZNF638:"",CTTNBP2:"",SRCAP:"",BCORL1:"",ZNF213:"",CNOT3:"",DEPDC5:"",ZMYND8:"",ADNP:"",CORO2A:"",SMC3:"",RAI1:"",SLC38A1:"",KIAA0240:"",CNOT6:"",BIRC6:"",MLL:"",PHF3:"",MED13L:"",MYBBP1A:"",KDM6B:"",ARHGEF11:"",EPHB2:"",KRBA1:"",MEN1:"",UGGT1:"",RTF1:"",MBD1:"",LMTK3:"",POGZ:"",FLG:"",PPRC1:"",CABLES2:"",SETBP1:"",PITPNC1:"",WDR4:"",VPS39:"",KIAA1586:"",CHD3:"",TANC2:"",TSNARE1:"",
DLK2:"",JMJD1C:"",CSRP2:"",MLXIP:"",UBE2O:"",ZBTB41:"",GPR139:"",ZNF594:"",SETD2:"",EP400:"",ZNF445:"",MTF1:"",TRRAP:"",PCDHB16:"",SLC25A29:"",ZNF860:"",TOPORS:"",SPTAN1:"",PHF2:"",ZNF311:"",TOP1:"",MBD5:"",TSSK2:"",ZNF585B:"",ITGB3:"",DVL2:"",SLC25A39:"",ARID1B:"",SEC61A1:"",DDX20:"",ANKS1A:"",GNAI3:"",NUP133:"",TCF3:"",IKBKG:"",GTF3C1:"",CAD:"",UIMC1:"",GCN1L1:"",RBM27:"",SUPT16H:"",EIF2C1:"",POLRMT:"",CRKL:"",DGCR14:"",SMCHD1:"",AXIN1:"",TSC2:"",HNRNPUL1:"",PLEKHA8:"",TRDMT1:"",AATF:"",ZNF451:"",
CISH:"",MSH6:"",ALMS1:"",APH1A:"",STK11:"",RPN2:"",IRF2BPL:"",DNMT3A:"",BCL11A:"",GNA13:"",ZMYM2:"",XPO5:"",CNOT1:"",KIAA0182:"",CDK4:"",DHX9:"",ACTL6A:"",TBR1:"",FAM129B:"",LRRC1:"",TET1:"",SMARCC2:"",DCAF5:"",USP3:"",XPR1:"",MCL1:"",METTL14:"",PPIP5K2:"",TLK2:"",MCPH1:"",FEZF2:"",AUTS2:"",PPP1R15B:"",KIAA1967:"",NFIA:"",VANGL2:"",GATAD2A:"","AC011498.1":"",C2CD3:"",SF1:"",RFWD3:"",HNRNPF:"",PWWP2A:"",PPM1D:"",TSEN34:"",TNKS:"",SMARCC1:"",RUVBL1:"",SCRIB:"",EHMT1:"",CADM1:"",DCC:"",ZNF292:"",ZKSCAN5:"",
ZNF813:"",DLL1:"",DCAF12:"",AP2S1:"",MAP4:"",NCKAP1:"",PKM2:"",SDHA:"",MAPK1:"",C14ORF129:"",DCAF11:"",CD99L2:"",CYB5B:"",STUB1:"",BCL7B:"",SOD2:"",ACTR1B:"",PPP1R7:"",SCP2:"",KLHDC3:"",PIN1:"",DNAJB9:"",GRSF1:"",YARS:"",SLC39A3:"",TAGLN3:"",SAR1B:"",PRDX3:"",FAM91A1:"",AK2:"",LTBP1:"",CSDA:"",NOTCH3:"",TTC38:"",FAT1:"",TRIP6:"",ITGA6:"",TBL1X:"",HSPB1:"",PLOD3:"",RAB34:"",ATP6V0E1:"",MAPKAPK3:"",CHST3:"",SOX9:"",PALLD:"",YAP1:"",TMX1:"",MSN:"",ITGB1:"",TCF7L1:"",PLOD2:"",NECAP2:"",FSTL1:"",ANXA5:"",
GPR98:"",CDCA7L:"",SLC4A2:"",IKBIP:"",FAM111A:"",ANTXR1:"",EMX2:"",GNG5:"",YES1:"",OXTR:"",SOX2:"",SPATA13:"",ZFP36L1:"",FLNA:"",SLC2A10:"",GNAS:"",AARSD1:"",GORASP2:"",TM4SF19:"",TRAPPC9:"",PAFAH1B2:"",GAK:"",HEATR8:"",THAP7:"",GPX1:""}.hasOwnProperty(b)?"#FF0000"==selectedColor?"#FAC0F2":"#FF0000":selectedColor}function initAboutB(){$("#aboutB").click(function(){$("#aboutContainer").toggle("slide",{direction:"right"},200)})}
function initSearchB(){$("#searchB").click(function(){$("#searchContainer").toggle("slide",{direction:"right"},200);$("#searchtext").focus()});$("#searchtext").keyup(function(b){13==b.keyCode&&nodeSearch()})}
function nodeSearch(){var b=$("#searchtext").val();$("#modelChart").is(":visible")?$("#modelChart"):$("#geneChart");d3.selectAll(".node").each(function(l,n){d3.select(this).select("circle").classed("nodeFound",!1);d3.select(this).select("text").text().toLowerCase()==b.toLowerCase()&&d3.select(this).select("circle").classed("nodeFound",!0)})}
(function(b){function l(){this._settings=[];this._extensions=[];this.regional=[];this.regional[""]={errorLoadingText:"Error loading",notSupportedText:"This browser does not support SVG"};this.local=this.regional[""];this._uuid=(new Date).getTime();var a;try{a=!(!window.ActiveXObject||!new ActiveXObject("RenesisX.RenesisCtrl"))}catch(c){a=!1}this._renesis=a}function n(a,c){this._svg=a;this._container=c;for(var k=0;k<b.svg._extensions.length;k++){var d=b.svg._extensions[k];this[d[0]]=new d[1](this)}}
function e(){this._path=""}function f(){this._parts=[]}function g(a){return a&&a.constructor==Array}b.extend(l.prototype,{markerClassName:"hasSVG",svgNS:"http://www.w3.org/2000/svg",xlinkNS:"http://www.w3.org/1999/xlink",_wrapperClass:n,_attrNames:{class_:"class",in_:"in",alignmentBaseline:"alignment-baseline",baselineShift:"baseline-shift",clipPath:"clip-path",clipRule:"clip-rule",colorInterpolation:"color-interpolation",colorInterpolationFilters:"color-interpolation-filters",colorRendering:"color-rendering",
dominantBaseline:"dominant-baseline",enableBackground:"enable-background",fillOpacity:"fill-opacity",fillRule:"fill-rule",floodColor:"flood-color",floodOpacity:"flood-opacity",fontFamily:"font-family",fontSize:"font-size",fontSizeAdjust:"font-size-adjust",fontStretch:"font-stretch",fontStyle:"font-style",fontVariant:"font-variant",fontWeight:"font-weight",glyphOrientationHorizontal:"glyph-orientation-horizontal",glyphOrientationVertical:"glyph-orientation-vertical",horizAdvX:"horiz-adv-x",horizOriginX:"horiz-origin-x",
imageRendering:"image-rendering",letterSpacing:"letter-spacing",lightingColor:"lighting-color",markerEnd:"marker-end",markerMid:"marker-mid",markerStart:"marker-start",stopColor:"stop-color",stopOpacity:"stop-opacity",strikethroughPosition:"strikethrough-position",strikethroughThickness:"strikethrough-thickness",strokeDashArray:"stroke-dasharray",strokeDashOffset:"stroke-dashoffset",strokeLineCap:"stroke-linecap",strokeLineJoin:"stroke-linejoin",strokeMiterLimit:"stroke-miterlimit",strokeOpacity:"stroke-opacity",
strokeWidth:"stroke-width",textAnchor:"text-anchor",textDecoration:"text-decoration",textRendering:"text-rendering",underlinePosition:"underline-position",underlineThickness:"underline-thickness",vertAdvY:"vert-adv-y",vertOriginY:"vert-origin-y",wordSpacing:"word-spacing",writingMode:"writing-mode"},_attachSVG:function(a,c){var k=a.namespaceURI==this.svgNS?a:null;a=k?null:a;if(!b(a||k).hasClass(this.markerClassName)){"string"==typeof c?c={loadURL:c}:"function"==typeof c&&(c={onLoad:c});b(a||k).addClass(this.markerClassName);
try{k||(k=document.createElementNS(this.svgNS,"svg"),k.setAttribute("version","1.1"),0<a.clientWidth&&k.setAttribute("width",a.clientWidth),0<a.clientHeight&&k.setAttribute("height",a.clientHeight),a.appendChild(k)),this._afterLoad(a,k,c||{})}catch(d){b.browser.msie?(a.id||(a.id="svg"+this._uuid++),this._settings[a.id]=c,a.innerHTML='<embed type="image/svg+xml" width="100%" height="100%" src="'+(c.initPath||"")+'blank.svg" pluginspage="http://www.adobe.com/svg/viewer/install/main.html"/>'):a.innerHTML=
'<p class="svg_error">'+this.local.notSupportedText+"</p>"}}},_registerSVG:function(){for(var a=0;a<document.embeds.length;a++){var c=document.embeds[a].parentNode;if(b(c).hasClass(b.svg.markerClassName)&&!b.data(c,"svgwrapper")){var k=null;try{k=document.embeds[a].getSVGDocument()}catch(d){setTimeout(b.svg._registerSVG,250);break}(k=k?k.documentElement:null)&&b.svg._afterLoad(c,k)}}},_afterLoad:function(a,c,k){k=k||this._settings[a.id];this._settings[a?a.id:""]=null;var d=new this._wrapperClass(c,
a);b.data(a||c,"svgwrapper",d);try{k.loadURL&&d.load(k.loadURL,k),k.settings&&d.configure(k.settings),k.onLoad&&!k.loadURL&&k.onLoad.apply(a||c,[d])}catch(m){alert(m)}},_getSVG:function(a){a="string"==typeof a?b(a)[0]:a.jquery?a[0]:a;return b.data(a,"svgwrapper")},_destroySVG:function(a){var c=b(a);c.hasClass(this.markerClassName)&&(c.removeClass(this.markerClassName),a.namespaceURI!=this.svgNS&&c.empty(),b.removeData(a,"svgwrapper"))},addExtension:function(a,c){this._extensions.push([a,c])},isSVGElem:function(a){return 1==
a.nodeType&&a.namespaceURI==b.svg.svgNS}});b.extend(n.prototype,{_width:function(){return this._container?this._container.clientWidth:this._svg.width},_height:function(){return this._container?this._container.clientHeight:this._svg.height},root:function(){return this._svg},configure:function(a,c,k){a.nodeName||(k=c,c=a,a=this._svg);if(k)for(k=a.attributes.length-1;0<=k;k--){var d=a.attributes.item(k);"onload"!=d.nodeName&&"version"!=d.nodeName&&"xmlns"!=d.nodeName.substring(0,5)&&a.attributes.removeNamedItem(d.nodeName)}for(var m in c)a.setAttribute(b.svg._attrNames[m]||
m,c[m]);return this},getElementById:function(a){return this._svg.ownerDocument.getElementById(a)},change:function(a,c){if(a)for(var k in c)null==c[k]?a.removeAttribute(b.svg._attrNames[k]||k):a.setAttribute(b.svg._attrNames[k]||k,c[k]);return this},_args:function(a,c,k){c.splice(0,0,"parent");c.splice(c.length,0,"settings");var d={},m=0;null!=a[0]&&a[0].jquery&&(a[0]=a[0][0]);null==a[0]||"object"==typeof a[0]&&a[0].nodeName||(d.parent=null,m=1);for(var g=0;g<a.length;g++)d[c[g+m]]=a[g];k&&b.each(k,
function(a,c){"object"==typeof d[c]&&(d.settings=d[c],d[c]=null)});return d},title:function(a,c,b){var d=this._args(arguments,["text"]),m=this._makeNode(d.parent,"title",d.settings||{});m.appendChild(this._svg.ownerDocument.createTextNode(d.text));return m},describe:function(a,c,b){var d=this._args(arguments,["text"]),m=this._makeNode(d.parent,"desc",d.settings||{});m.appendChild(this._svg.ownerDocument.createTextNode(d.text));return m},defs:function(a,c,k){var d=this._args(arguments,["id"],["id"]);
return this._makeNode(d.parent,"defs",b.extend(d.id?{id:d.id}:{},d.settings||{}))},symbol:function(a,c,k,d,m,g,e){var f=this._args(arguments,["id","x1","y1","width","height"]);return this._makeNode(f.parent,"symbol",b.extend({id:f.id,viewBox:f.x1+" "+f.y1+" "+f.width+" "+f.height},f.settings||{}))},marker:function(a,c,k,d,m,g,e,f){var p=this._args(arguments,"id refX refY mWidth mHeight orient".split(" "),["orient"]);return this._makeNode(p.parent,"marker",b.extend({id:p.id,refX:p.refX,refY:p.refY,
markerWidth:p.mWidth,markerHeight:p.mHeight,orient:p.orient||"auto"},p.settings||{}))},style:function(a,c,k){var d=this._args(arguments,["styles"]),m=this._makeNode(d.parent,"style",b.extend({type:"text/css"},d.settings||{}));m.appendChild(this._svg.ownerDocument.createTextNode(d.styles));b.browser.opera&&b("head").append('<style type="text/css">'+d.styles+"</style>");return m},script:function(a,c,k,d){var m=this._args(arguments,["script","type"],["type"]),g=this._makeNode(m.parent,"script",b.extend({type:m.type||
"text/javascript"},m.settings||{}));g.appendChild(this._svg.ownerDocument.createTextNode(m.script));b.browser.mozilla||b.globalEval(m.script);return g},linearGradient:function(a,c,k,d,m,g,e,f){var p=this._args(arguments,"id stops x1 y1 x2 y2".split(" "),["x1"]),l=b.extend({id:p.id},null!=p.x1?{x1:p.x1,y1:p.y1,x2:p.x2,y2:p.y2}:{});return this._gradient(p.parent,"linearGradient",b.extend(l,p.settings||{}),p.stops)},radialGradient:function(a,c,k,d,m,g,e,f,p){var l=this._args(arguments,"id stops cx cy r fx fy".split(" "),
["cx"]),n=b.extend({id:l.id},null!=l.cx?{cx:l.cx,cy:l.cy,r:l.r,fx:l.fx,fy:l.fy}:{});return this._gradient(l.parent,"radialGradient",b.extend(n,l.settings||{}),l.stops)},_gradient:function(a,c,k,d){a=this._makeNode(a,c,k);for(c=0;c<d.length;c++)k=d[c],this._makeNode(a,"stop",b.extend({offset:k[0],stopColor:k[1]},null!=k[2]?{stopOpacity:k[2]}:{}));return a},pattern:function(a,c,k,d,m,g,e,f,l,n,s){var r=this._args(arguments,"id x y width height vx vy vwidth vheight".split(" "),["vx"]),u=b.extend({id:r.id,
x:r.x,y:r.y,width:r.width,height:r.height},null!=r.vx?{viewBox:r.vx+" "+r.vy+" "+r.vwidth+" "+r.vheight}:{});return this._makeNode(r.parent,"pattern",b.extend(u,r.settings||{}))},clipPath:function(a,c,k,d){var m=this._args(arguments,["id","units"]);m.units=m.units||"userSpaceOnUse";return this._makeNode(m.parent,"clipPath",b.extend({id:m.id,clipPathUnits:m.units},m.settings||{}))},mask:function(a,c,k,d,m,g,e){var f=this._args(arguments,["id","x","y","width","height"]);return this._makeNode(f.parent,
"mask",b.extend({id:f.id,x:f.x,y:f.y,width:f.width,height:f.height},f.settings||{}))},createPath:function(){return new e},createText:function(){return new f},svg:function(a,c,k,d,m,g,f,e,l,n){var s=this._args(arguments,"x y width height vx vy vwidth vheight".split(" "),["vx"]),r=b.extend({x:s.x,y:s.y,width:s.width,height:s.height},null!=s.vx?{viewBox:s.vx+" "+s.vy+" "+s.vwidth+" "+s.vheight}:{});return this._makeNode(s.parent,"svg",b.extend(r,s.settings||{}))},group:function(a,c,k){var d=this._args(arguments,
["id"],["id"]);return this._makeNode(d.parent,"g",b.extend({id:d.id},d.settings||{}))},use:function(a,c,k,d,g,f,e){var q=this._args(arguments,["x","y","width","height","ref"]);"string"==typeof q.x&&(q.ref=q.x,q.settings=q.y,q.x=q.y=q.width=q.height=null);var l=this._makeNode(q.parent,"use",b.extend({x:q.x,y:q.y,width:q.width,height:q.height},q.settings||{}));l.setAttributeNS(b.svg.xlinkNS,"href",q.ref);return l},link:function(a,c,k){var d=this._args(arguments,["ref"]),g=this._makeNode(d.parent,"a",
d.settings);g.setAttributeNS(b.svg.xlinkNS,"href",d.ref);return g},image:function(a,c,k,d,g,f,e){var l=this._args(arguments,["x","y","width","height","ref"]),p=this._makeNode(l.parent,"image",b.extend({x:l.x,y:l.y,width:l.width,height:l.height},l.settings||{}));p.setAttributeNS(b.svg.xlinkNS,"href",l.ref);return p},path:function(a,c,k){var d=this._args(arguments,["path"]);return this._makeNode(d.parent,"path",b.extend({d:d.path.path?d.path.path():d.path},d.settings||{}))},rect:function(a,c,k,d,g,
f,e,l){var p=this._args(arguments,"x y width height rx ry".split(" "),["rx"]);return this._makeNode(p.parent,"rect",b.extend({x:p.x,y:p.y,width:p.width,height:p.height},p.rx?{rx:p.rx,ry:p.ry}:{},p.settings||{}))},circle:function(a,c,k,d,g){var f=this._args(arguments,["cx","cy","r"]);return this._makeNode(f.parent,"circle",b.extend({cx:f.cx,cy:f.cy,r:f.r},f.settings||{}))},ellipse:function(a,c,k,d,g,f){var e=this._args(arguments,["cx","cy","rx","ry"]);return this._makeNode(e.parent,"ellipse",b.extend({cx:e.cx,
cy:e.cy,rx:e.rx,ry:e.ry},e.settings||{}))},line:function(a,c,k,d,g,f){var e=this._args(arguments,["x1","y1","x2","y2"]);return this._makeNode(e.parent,"line",b.extend({x1:e.x1,y1:e.y1,x2:e.x2,y2:e.y2},e.settings||{}))},polyline:function(a,c,b){var d=this._args(arguments,["points"]);return this._poly(d.parent,"polyline",d.points,d.settings)},polygon:function(a,c,b){var d=this._args(arguments,["points"]);return this._poly(d.parent,"polygon",d.points,d.settings)},_poly:function(a,c,k,d){for(var g="",
f=0;f<k.length;f++)g+=k[f].join()+" ";return this._makeNode(a,c,b.extend({points:b.trim(g)},d||{}))},text:function(a,c,k,d,f){var e=this._args(arguments,["x","y","value"]);"string"==typeof e.x&&4>arguments.length&&(e.value=e.x,e.settings=e.y,e.x=e.y=null);return this._text(e.parent,"text",e.value,b.extend({x:e.x&&g(e.x)?e.x.join(" "):e.x,y:e.y&&g(e.y)?e.y.join(" "):e.y},e.settings||{}))},textpath:function(a,c,k,d){var e=this._args(arguments,["path","value"]),g=this._text(e.parent,"textPath",e.value,
e.settings||{});g.setAttributeNS(b.svg.xlinkNS,"href",e.path);return g},_text:function(a,c,k,d){a=this._makeNode(a,c,d);if("string"==typeof k)a.appendChild(a.ownerDocument.createTextNode(k));else for(c=0;c<k._parts.length;c++)if(d=k._parts[c],"tspan"==d[0]){var e=this._makeNode(a,d[0],d[2]);e.appendChild(a.ownerDocument.createTextNode(d[1]));a.appendChild(e)}else"tref"==d[0]?(e=this._makeNode(a,d[0],d[2]),e.setAttributeNS(b.svg.xlinkNS,"href",d[1]),a.appendChild(e)):"textpath"==d[0]?(e=b.extend({},
d[2]),e.href=null,e=this._makeNode(a,d[0],e),e.setAttributeNS(b.svg.xlinkNS,"href",d[2].href),e.appendChild(a.ownerDocument.createTextNode(d[1])),a.appendChild(e)):a.appendChild(a.ownerDocument.createTextNode(d[1]));return a},other:function(a,c,b){var d=this._args(arguments,["name"]);return this._makeNode(d.parent,d.name,d.settings||{})},_makeNode:function(a,c,k){a=a||this._svg;var d=this._svg.ownerDocument.createElementNS(b.svg.svgNS,c);for(c in k){var e=k[c];null==e||null==e||"string"==typeof e&&
""==e||d.setAttribute(b.svg._attrNames[c]||c,e)}a.appendChild(d);return d},add:function(a,c){var k=this._args(1==arguments.length?[null,a]:arguments,["node"]),d=this;k.parent=k.parent||this._svg;k.node=k.node.jquery?k.node:b(k.node);try{if(b.svg._renesis)throw"Force traversal";k.parent.appendChild(k.node.cloneNode(!0))}catch(e){k.node.each(function(){var a=d._cloneAsSVG(this);a&&k.parent.appendChild(a)})}return this},clone:function(a,c){var k=this,d=this._args(1==arguments.length?[null,a]:arguments,
["node"]);d.parent=d.parent||this._svg;d.node=d.node.jquery?d.node:b(d.node);var e=[];d.node.each(function(){var a=k._cloneAsSVG(this);a&&(a.id="",d.parent.appendChild(a),e.push(a))});return e},_cloneAsSVG:function(a){var c=null;if(1==a.nodeType){for(var c=this._svg.ownerDocument.createElementNS(b.svg.svgNS,this._checkName(a.nodeName)),k=0;k<a.attributes.length;k++){var d=a.attributes.item(k);"xmlns"!=d.nodeName&&d.nodeValue&&("xlink"==d.prefix?c.setAttributeNS(b.svg.xlinkNS,d.localName||d.baseName,
d.nodeValue):c.setAttribute(this._checkName(d.nodeName),d.nodeValue))}for(k=0;k<a.childNodes.length;k++)(d=this._cloneAsSVG(a.childNodes[k]))&&c.appendChild(d)}else if(3==a.nodeType)b.trim(a.nodeValue)&&(c=this._svg.ownerDocument.createTextNode(a.nodeValue));else if(4==a.nodeType&&b.trim(a.nodeValue))try{c=this._svg.ownerDocument.createCDATASection(a.nodeValue)}catch(e){c=this._svg.ownerDocument.createTextNode(a.nodeValue.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;"))}return c},
_checkName:function(a){a="A"<=a.substring(0,1)&&"Z">=a.substring(0,1)?a.toLowerCase():a;return"svg:"==a.substring(0,4)?a.substring(4):a},load:function(a,c){c="boolean"==typeof c?{addTo:c}:"function"==typeof c?{onLoad:c}:"string"==typeof c?{parent:c}:"object"==typeof c&&c.nodeName?{parent:c}:"object"==typeof c&&c.jquery?{parent:c}:c||{};c.parent||c.addTo||this.clear(!1);var k=[this._svg.getAttribute("width"),this._svg.getAttribute("height")],d=this,e=function(a){a=b.svg.local.errorLoadingText+": "+
a;c.onLoad?c.onLoad.apply(d._container||d._svg,[d,a]):d.text(null,10,20,a)},g=function(a){var c=new ActiveXObject("Microsoft.XMLDOM");c.validateOnParse=!1;c.resolveExternals=!1;c.async=!1;c.loadXML(a);return 0!=c.parseError.errorCode?(e(c.parseError.reason),null):c},f=function(a){if(a)if("svg"!=a.documentElement.nodeName){var g=a.getElementsByTagName("parsererror"),f=g.length?g[0].getElementsByTagName("div"):[];e(g.length?(f.length?f[0]:g[0]).firstChild.nodeValue:"???")}else{for(var g=c.parent?b(c.parent)[0]:
d._svg,l={},f=0;f<a.documentElement.attributes.length;f++){var n=a.documentElement.attributes.item(f);"version"!=n.nodeName&&"xmlns"!=n.nodeName.substring(0,5)&&(l[n.nodeName]=n.nodeValue)}d.configure(g,l,!c.parent);a=a.documentElement.childNodes;for(f=0;f<a.length;f++)try{if(b.svg._renesis)throw"Force traversal";g.appendChild(d._svg.ownerDocument.importNode(a[f],!0));"script"==a[f].nodeName&&b.globalEval(a[f].textContent)}catch(t){d.add(g,a[f])}c.changeSize||d.configure(g,{width:k[0],height:k[1]});
c.onLoad&&c.onLoad.apply(d._container||d._svg,[d])}};a.match("<svg")?f(b.browser.msie?g(a):(new DOMParser).parseFromString(a,"text/xml")):b.ajax({url:a,dataType:b.browser.msie?"text":"xml",success:function(a){f(b.browser.msie?g(a):a)},error:function(a,c,b){e(c+(b?" "+b.message:""))}});return this},remove:function(a){a=a.jquery?a[0]:a;a.parentNode.removeChild(a);return this},clear:function(a){for(a&&this.configure({},!0);this._svg.firstChild;)this._svg.removeChild(this._svg.firstChild);return this},
toSVG:function(a){a=a||this._svg;return"undefined"==typeof XMLSerializer?this._toSVG(a):(new XMLSerializer).serializeToString(a)},_toSVG:function(a){var c="";if(!a)return c;if(3==a.nodeType)c=a.nodeValue;else if(4==a.nodeType)c="<![CDATA["+a.nodeValue+"]]\x3e";else{c="<"+a.nodeName;if(a.attributes)for(var k=0;k<a.attributes.length;k++){var d=a.attributes.item(k);""==b.trim(d.nodeValue)||d.nodeValue.match(/^\[object/)||d.nodeValue.match(/^function/)||(c+=" "+(d.namespaceURI==b.svg.xlinkNS?"xlink:":
"")+d.nodeName+'="'+d.nodeValue+'"')}if(a.firstChild){c+=">";for(k=a.firstChild;k;)c+=this._toSVG(k),k=k.nextSibling;c+="</"+a.nodeName+">"}else c+="/>"}return c}});b.extend(e.prototype,{reset:function(){this._path="";return this},move:function(a,c,b){b=g(a)?c:b;return this._coords(b?"m":"M",a,c)},line:function(a,c,b){b=g(a)?c:b;return this._coords(b?"l":"L",a,c)},horiz:function(a,c){this._path+=(c?"h":"H")+(g(a)?a.join(" "):a);return this},vert:function(a,c){this._path+=(c?"v":"V")+(g(a)?a.join(" "):
a);return this},curveC:function(a,c,b,d,e,f,l){l=g(a)?c:l;return this._coords(l?"c":"C",a,c,b,d,e,f)},smoothC:function(a,c,b,d,e){e=g(a)?c:e;return this._coords(e?"s":"S",a,c,b,d)},curveQ:function(a,c,b,d,e){e=g(a)?c:e;return this._coords(e?"q":"Q",a,c,b,d)},smoothQ:function(a,c,b){b=g(a)?c:b;return this._coords(b?"t":"T",a,c)},_coords:function(a,c,b,d,e,f,l){if(g(c))for(b=0;b<c.length;b++)d=c[b],this._path+=(0==b?a:" ")+d[0]+","+d[1]+(4>d.length?"":" "+d[2]+","+d[3]+(6>d.length?"":" "+d[4]+","+d[5]));
else this._path+=a+c+","+b+(null==d?"":" "+d+","+e+(null==f?"":" "+f+","+l));return this},arc:function(a,c,b,d,e,f,l,n){n=g(a)?c:n;this._path+=n?"a":"A";if(g(a))for(c=0;c<a.length;c++)b=a[c],this._path+=(0==c?"":" ")+b[0]+","+b[1]+" "+b[2]+" "+(b[3]?"1":"0")+","+(b[4]?"1":"0")+" "+b[5]+","+b[6];else this._path+=a+","+c+" "+b+" "+(d?"1":"0")+","+(e?"1":"0")+" "+f+","+l;return this},close:function(){this._path+="z";return this},path:function(){return this._path}});e.prototype.moveTo=e.prototype.move;
e.prototype.lineTo=e.prototype.line;e.prototype.horizTo=e.prototype.horiz;e.prototype.vertTo=e.prototype.vert;e.prototype.curveCTo=e.prototype.curveC;e.prototype.smoothCTo=e.prototype.smoothC;e.prototype.curveQTo=e.prototype.curveQ;e.prototype.smoothQTo=e.prototype.smoothQ;e.prototype.arcTo=e.prototype.arc;b.extend(f.prototype,{reset:function(){this._parts=[];return this},string:function(a){this._parts[this._parts.length]=["text",a];return this},span:function(a,b){this._parts[this._parts.length]=
["tspan",a,b];return this},ref:function(a,b){this._parts[this._parts.length]=["tref",a,b];return this},path:function(a,c,e){this._parts[this._parts.length]=["textpath",c,b.extend({href:a},e||{})];return this}});b.fn.svg=function(a){var c=Array.prototype.slice.call(arguments,1);return"string"==typeof a&&"get"==a?b.svg["_"+a+"SVG"].apply(b.svg,[this[0]].concat(c)):this.each(function(){"string"==typeof a?b.svg["_"+a+"SVG"].apply(b.svg,[this].concat(c)):b.svg._attachSVG(this,a||{})})};b.svg=new l})(jQuery);
(function(b){function l(e){for(var f=0;f<e.length;f++)if(1==e[f].nodeType&&e[f].namespaceURI==b.svg.svgNS)return!0;return!1}b.fn.addClass=function(e){return function(f){f=f||"";return this.each(function(){if(b.svg.isSVGElem(this)){var g=this;b.each(f.split(/\s+/),function(a,c){var e=g.className?g.className.baseVal:g.getAttribute("class");-1==b.inArray(c,e.split(/\s+/))&&(e+=(e?" ":"")+c,g.className?g.className.baseVal=e:g.setAttribute("class",e))})}else e.apply(b(this),[f])})}}(b.fn.addClass);b.fn.removeClass=
function(e){return function(f){f=f||"";return this.each(function(){if(b.svg.isSVGElem(this)){var g=this;b.each(f.split(/\s+/),function(a,c){var e=g.className?g.className.baseVal:g.getAttribute("class"),e=b.grep(e.split(/\s+/),function(a,b){return a!=c}).join(" ");g.className?g.className.baseVal=e:g.setAttribute("class",e)})}else e.apply(b(this),[f])})}}(b.fn.removeClass);b.fn.toggleClass=function(e){return function(f,g){return this.each(function(){b.svg.isSVGElem(this)?("boolean"!==typeof g&&(g=!b(this).hasClass(f)),
b(this)[(g?"add":"remove")+"Class"](f)):e.apply(b(this),[f,g])})}}(b.fn.toggleClass);b.fn.hasClass=function(e){return function(f){f=f||"";var g=!1;this.each(function(){if(b.svg.isSVGElem(this)){var a=(this.className?this.className.baseVal:this.getAttribute("class")).split(/\s+/);g=-1<b.inArray(f,a)}else g=e.apply(b(this),[f]);return!g});return g}}(b.fn.hasClass);b.fn.attr=function(e){return function(f,g,a){if("string"===typeof f&&void 0===g){var c=e.apply(this,[f]);if(c&&c.baseVal&&null!=c.baseVal.numberOfItems)if(g=
"",c=c.baseVal,"transform"==f){for(var k=0;k<c.numberOfItems;k++){var d=c.getItem(k);switch(d.type){case 1:g+=" matrix("+d.matrix.a+","+d.matrix.b+","+d.matrix.c+","+d.matrix.d+","+d.matrix.e+","+d.matrix.f+")";break;case 2:g+=" translate("+d.matrix.e+","+d.matrix.f+")";break;case 3:g+=" scale("+d.matrix.a+","+d.matrix.d+")";break;case 4:g+=" rotate("+d.angle+")";break;case 5:g+=" skewX("+d.angle+")";break;case 6:g+=" skewY("+d.angle+")"}}c=g.substring(1)}else c=c.getItem(0).valueAsString;return c&&
c.baseVal?c.baseVal.valueAsString:c}var l=f;"string"===typeof f&&(l={},l[f]=g);return this.each(function(){if(b.svg.isSVGElem(this))for(var c in l){var d=b.isFunction(l[c])?l[c]():l[c];a?this.style[c]=d:this.setAttribute(c,d)}else e.apply(b(this),[f,g,a])})}}(b.fn.attr);b.fn.removeAttr=function(e){return function(f){return this.each(function(){b.svg.isSVGElem(this)?this[f]&&this[f].baseVal?this[f].baseVal.value="":this.setAttribute(f,""):e.apply(b(this),[f])})}}(b.fn.removeAttr);b.extend(b.cssNumber,
{stopOpacity:!0,strokeMitrelimit:!0,strokeOpacity:!0});b.cssProps&&(b.css=function(e){return function(f,g,a){return(g.match(/^svg.*/)?b(f).attr(b.cssProps[g]||g):"")||e(f,g,a)}}(b.css));b.expr.relative["+"]=function(b){return function(f,g,a){b(f,g,a||l(f))}}(b.expr.relative["+"]);b.expr.relative[">"]=function(b){return function(f,g,a){b(f,g,a||l(f))}}(b.expr.relative[">"]);b.expr.relative[""]=function(b){return function(f,g,a){b(f,g,a||l(f))}}(b.expr.relative[""]);b.expr.relative["~"]=function(b){return function(f,
g,a){b(f,g,a||l(f))}}(b.expr.relative["~"]);b.expr.find.ID=function(e){return function(f,g,a){return b.svg.isSVGElem(g)?[g.ownerDocument.getElementById(f[1])]:e(f,g,a)}}(b.expr.find.ID);var n=document.createElement("div");n.appendChild(document.createComment(""));0<n.getElementsByTagName("*").length&&(b.expr.find.TAG=function(b,f){var g=f.getElementsByTagName(b[1]);if("*"===b[1]){for(var a=[],c=0;g[c]||g.item(c);c++)1===(g[c]||g.item(c)).nodeType&&a.push(g[c]||g.item(c));g=a}return g});b.expr.preFilter.CLASS=
function(e,f,g,a,c,k){e=" "+e[1].replace(/\\/g,"")+" ";if(k)return e;k=0;for(var d={};null!=d;k++){d=f[k];if(!d)try{d=f.item(k)}catch(l){}if(d){var n=b.svg.isSVGElem(d)?(d.className?d.className.baseVal:"")||d.getAttribute("class"):d.className;c^(n&&-1<(" "+n+" ").indexOf(e))?g||a.push(d):g&&(f[k]=!1)}}return!1};b.expr.filter.CLASS=function(e,f){return-1<(" "+(b.svg.isSVGElem(e)?e.className?e.className.baseVal:e.getAttribute("class"):e.className)+" ").indexOf(f)};b.expr.filter.ATTR=function(e){return function(f,
g){var a=null;b.svg.isSVGElem(f)&&(a=g[1],b.expr.attrHandle[a]=function(b){return(b=b.getAttribute(a))&&b.baseVal||b});var c=e(f,g);a&&(b.expr.attrHandle[a]=null);return c}}(b.expr.filter.ATTR)})(jQuery);